# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do

  end
  desc "Push a new beta build to TestFlight"
  lane :beta do
      default_payloads: [:git_branch, :git_author, :last_git_commit], # Optional, lets you specify a whitelist of default payloads to include. Pass an empty array to suppress all the default payloads.
            # Don't add this key, or pass nil, if you want all the default payloads. The available default payloads are: `lane`, `test_result`, `git_branch`, `git_author`, `last_git_commit`, `last_git_commit_hash`.
      attachment_properties: { # Optional, lets you specify any other properties available for attachments in the slack API (see https://api.slack.com/docs/attachments).
           # This hash is deep merged with the existing properties set using the other properties above. This allows your own fields properties to be appended to the existing fields that were created using the `payload` property for instance.
        thumb_url: "https://averylamp.me/images/Pear.jpg",
      }
    )
    increment_build_number
    build_app(workspace: "Imagear.xcworkspace", scheme: "Development")
    upload_to_testflight
    slack(
      slack_url: "https://hooks.slack.com/services/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",
      message: "New DEV Beta version of App Released!",
      channel: "#imagear",  # Optional, by default will post to the default channel configured for the POST URL.
      success: true,        # Optional, defaults to true.
      payload: {  # Optional, lets you specify any number of your own Slack attachments.
        "Build Date" => Time.new.to_s,
        "Built by" => "Fastlane",
      },

      default_payloads: [:git_branch, :git_author, :last_git_commit], # Optional, lets you specify a whitelist of default payloads to include. Pass an empty array to suppress all the default payloads.
            # Don't add this key, or pass nil, if you want all the default payloads. The available default payloads are: `lane`, `test_result`, `git_branch`, `git_author`, `last_git_commit`, `last_git_commit_hash`.
      attachment_properties: { # Optional, lets you specify any other properties available for attachments in the slack API (see https://api.slack.com/docs/attachments).
           # This hash is deep merged with the existing properties set using the other properties above. This allows your own fields properties to be appended to the existing fields that were created using the `payload` property for instance.
        thumb_url: "https://averylamp.me/images/Pear.jpg",
      }
    )
    upload_symbols
  end
  desc "Push a build to TestFlight for release"
  lane :release do
    increment_build_number
    build_app(workspace: "Imagear.xcworkspace", scheme: "Production")
    upload_to_testflight
    slack(
      slack_url: "https://hooks.slack.com/services/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",
      message: "New PROD Beta version of App Released!",
      channel: "#general",  # Optional, by default will post to the default channel configured for the POST URL.
      success: true,        # Optional, defaults to true.
      payload: {  # Optional, lets you specify any number of your own Slack attachments.
        "Build Date" => Time.new.to_s,
        "Built by" => "Fastlane",
      },

      default_payloads: [:git_branch, :git_author, :last_git_commit], # Optional, lets you specify a whitelist of default payloads to include. Pass an empty array to suppress all the default payloads.
            # Don't add this key, or pass nil, if you want all the default payloads. The available default payloads are: `lane`, `test_result`, `git_branch`, `git_author`, `last_git_commit`, `last_git_commit_hash`.
      attachment_properties: { # Optional, lets you specify any other properties available for attachments in the slack API (see https://api.slack.com/docs/attachments).
           # This hash is deep merged with the existing properties set using the other properties above. This allows your own fields properties to be appended to the existing fields that were created using the `payload` property for instance.
        thumb_url: "https://averylamp.me/images/Pear.jpg",
      }
    )
    upload_symbols
  end
  # desc "Upload Symbols"
  # lane :upload_symbols do
  #   download_dsyms(output_directory: 'dsyms')
  #   sentry_upload_dsym(
  #     auth_token: '602ec7c2764146e29de4ec0c60c6fb6acece827d74be480e8e6b2b06ad8d22fc',
  #     org_slug: 'setup-and-matchmake-pear',
  #     project_slug: 'pear',
  #   )
  # end
  desc "Runs Tests"
  lane :test do
    run_tests(scheme: "Production")
  end

end
